export const CHOOSE_ITEM = 'CHOOSE_ITEM';

export const GET_ITEM_FAILED = 'GET_ITEM_FAILED';
export const GET_ITEM_REQUESTED = 'GET_ITEM_REQUESTED';
export const GET_ITEM_SUCCEEDED = 'GET_ITEM_SUCCEEDED';

export const GET_PASSENGERS_FAILED = 'GET_PASSENGERS_FAILED';
export const GET_PASSENGERS_REQUESTED = 'GET_PASSENGERS_REQUESTED';
export const GET_PASSENGERS_SUCCEEDED = 'GET_PASSENGERS_SUCCEEDED';

export const GET_PLANETS_FAILED = 'GET_PLANETS_FAILED';
export const GET_PLANETS_REQUESTED = 'GET_PLANETS_REQUESTED';
export const GET_PLANETS_SUCCEEDED = 'GET_PLANETS_SUCCEEDED';

export const GET_PRICE_FAILED = 'GET_PRICE_FAILED';
export const GET_PRICE_REQUESTED = 'GET_PRICE_REQUESTED';
export const GET_PRICE_SUCCEEDED = 'GET_PRICE_SUCCEEDED';

export const GET_STARSHIPS_FAILED = 'GET_STARSHIPS_FAILED';
export const GET_STARSHIPS_REQUESTED = 'GET_STARSHIPS_REQUESTED';
export const GET_STARSHIPS_SUCCEEDED = 'GET_STARSHIPS_SUCCEEDED';

export const KEY_ITEM_CHANGE = 'KEY_ITEM_CHANGE';

export const ON_RESIZE_WINDOW = 'ON_RESIZE_WINDOW';

export const POST_RIDE_FAILED = 'POST_RIDE_FAILED';
export const POST_RIDE_REQUESTED = 'POST_RIDE_REQUESTED';
export const POST_RIDE_SUCCEEDED = 'POST_RIDE_SUCCEEDED';

export const RESTART = 'RESTART';

export const STEP_CHANGE = 'STEP_CHANGE';
